// Copyright (C) 2013 by Glyn Matthews
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

#include <gtest/gtest.h>
#include <boost/algorithm/string/trim.hpp>
#include "network/http/v2/client/response_parser.hpp"

namespace http = network::http::v2;

namespace {
  const std::string input =
    "HTTP/1.0 200 OK\r\n"
    "Date: Wed, 11 Sep 2013 05:50:12 GMT\r\n"
    "Server: Apache/2.2.15 (Red Hat)\r\n"
    "Last-Modified: Fri, 28 Mar 2008 17:26:33 GMT\r\n"
    "ETag: \"240a0b-53a-449829a786440\"\r\n"
    "Accept-Ranges: bytes\r\n"
    "Content-Length: 1338\r\n"
    "Connection: close\r\n"
    "Content-Type: text/plain\r\n"
    "\r\n"
    "Boost Software License - Version 1.0 - August 17th, 2003\n"
    "\n"
    "Permission is hereby granted, free of charge, to any person or organization\n"
    "obtaining a copy of the software and accompanying documentation covered by\n"
    "this license (the \"Software\") to use, reproduce, display, distribute,\n"
    "execute, and transmit the Software, and to prepare derivative works of the\n"
    "Software, and to permit third-parties to whom the Software is furnished to\n"
    "do so, all subject to the following:\n"
    "\n"
    "The copyright notices in the Software and this entire statement, including\n"
    "the above license grant, this restriction and the following disclaimer,\n"
    "must be included in all copies of the Software, in whole or in part, and\n"
    "all derivative works of the Software, unless such copies or derivative\n"
    "works are solely in the form of machine-executable object code generated by\n"
    "a source language processor.\n"
    "\n"
    "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
    "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
    "FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT\n"
    "SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE\n"
    "FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,\n"
    "ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n"
    "DEALINGS IN THE SOFTWARE.\n"
    ;

  inline
  std::string trimmed_string(std::string::const_iterator first,
                             std::string::const_iterator last) {
    return boost::trim_right_copy(std::string(first, last));
  }
} // namespace

TEST(response_parser_test, parse_version) {
  http::response_parser parser;
  auto part = parser.parse_until(http::response_parser::http_version_minor, input);
  ASSERT_TRUE(std::get<0>(part));
  ASSERT_EQ("HTTP/1.0", trimmed_string(std::begin(std::get<1>(part)), std::end(std::get<1>(part))));
}

TEST(response_parser_test, parse_version_major) {
  http::response_parser parser;
  auto part_1 = parser.parse_until(http::response_parser::http_version_slash, input);
  ASSERT_TRUE(std::get<0>(part_1));
  auto part_2 = parser.parse_until(http::response_parser::http_version_major,
                                     boost::make_iterator_range(std::end(std::get<1>(part_1)),
                                                                std::end(input)));
  ASSERT_TRUE(std::get<0>(part_2));
  ASSERT_EQ("1", trimmed_string(std::begin(std::get<1>(part_2)), std::end(std::get<1>(part_2))));
}

TEST(response_parser_test, parse_version_major_minor) {
  http::response_parser parser;
  auto part_1 = parser.parse_until(http::response_parser::http_version_slash, input);
  ASSERT_TRUE(std::get<0>(part_1));
  auto part_2 = parser.parse_until(http::response_parser::http_version_minor,
                                     boost::make_iterator_range(std::end(std::get<1>(part_1)),
                                                                std::end(input)));
  ASSERT_TRUE(std::get<0>(part_2));
  ASSERT_EQ("1.0", trimmed_string(std::begin(std::get<1>(part_2)), std::end(std::get<1>(part_2))));
}

TEST(response_parser_test, parse_status_digit) {
  http::response_parser parser;
  auto part_1 = parser.parse_until(http::response_parser::http_version_done, input);
  ASSERT_TRUE(std::get<0>(part_1));
  auto part_2 = parser.parse_until(http::response_parser::http_status_digit,
                                     boost::make_iterator_range(std::end(std::get<1>(part_1)),
                                                                std::end(input)));
  ASSERT_TRUE(std::get<0>(part_2));
  ASSERT_EQ("2", trimmed_string(std::begin(std::get<1>(part_2)), std::end(std::get<1>(part_2))));
}

TEST(response_parser_test, parse_status_code) {
  http::response_parser parser;
  auto part_1 = parser.parse_until(http::response_parser::http_version_done, input);
  ASSERT_TRUE(std::get<0>(part_1));
  auto part_2 = parser.parse_until(http::response_parser::http_status_done,
                                     boost::make_iterator_range(std::end(std::get<1>(part_1)),
                                                                std::end(input)));
  ASSERT_TRUE(std::get<0>(part_2));
  ASSERT_EQ("200", trimmed_string(std::begin(std::get<1>(part_2)), std::end(std::get<1>(part_2))));
}

TEST(response_parser_test, parse_status_message) {
  http::response_parser parser;
  auto part_1 = parser.parse_until(http::response_parser::http_status_done, input);
  ASSERT_TRUE(std::get<0>(part_1));
  auto part_2 = parser.parse_until(http::response_parser::http_status_message_done,
                                     boost::make_iterator_range(std::end(std::get<1>(part_1)),
                                                                std::end(input)));
  ASSERT_TRUE(std::get<0>(part_2));
  ASSERT_EQ("OK", trimmed_string(std::begin(std::get<1>(part_2)), std::end(std::get<1>(part_2))));
}
